#!/bin/sh
#
# Start/stop aesdchar kernel module
#
# Written using DeepSeek: https://chat.deepseek.com/share/4m9wymxypxs883oyy6
#

case "$1" in
    start)
        echo "Loading aesdchar kernel module"
        modprobe aesdchar
        ;;
    stop)
        echo "Unloading aesdchar kernel module"
        rmmod aesdchar
        ;;
    restart|reload)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
